### ISSUE TITLE
Creating New Index File Dwpency not found

### ISSUE THREAD

**Issue by TalhaAkkas** [DigitalCloud/nova-custom-views#11]
I am trying to create a custom index file 
Here is full dump of console

Ms-MacBook-Pro:emlak m.talhabuyukakkaslar$ php artisan nova:views estate index

 Would you like to compile the views's assets? (yes/no) [yes]:
 > yes

> @ dev /Applications/MAMP/htdocs/emlak/nova-components/views/estate
> npm run development

> @ development /Applications/MAMP/htdocs/emlak/nova-components/views/estate
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 11% building modules 12/13 modules 1 active ...lak/nova/resources/js/views/Index.vue{ parser: "babylon" } is deprecated; we now treat it as { parser: "babel" }.
 95% emitting                                                                        

 ERROR  Failed to compile with 1 errors                                                                                                                 13:10:55

This dependency was not found:

* !!babel-loader?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!../../../../nova-components/views/estate/node_modules/vue-loader/lib/selector?type=script&index=0!./Index.vue in /Applications/MAMP/htdocs/emlak/nova/resources/js/views/Index.vue

To install it, you can run: npm install --save !!babel-loader?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!../../../../nova-components/views/estate/node_modules/vue-loader/lib/selector?type=script&index=0!./Index.vue
        Asset     Size  Chunks             Chunk Names
 /js/views.js    35 kB       0  [emitted]  /js/views
css/views.css  0 bytes       0  [emitted]  /js/views

ERROR in /Applications/MAMP/htdocs/emlak/nova/resources/js/views/Index.vue
Module not found: Error: Can't resolve 'babel-loader' in '/Applications/MAMP/htdocs/emlak/nova/resources/js/views'
 @ /Applications/MAMP/htdocs/emlak/nova/resources/js/views/Index.vue 4:21-390
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/views/Index.vue
 @ ./resources/js/views/Index.vue
 @ ./resources/js/views ^\.\/.*$
 @ ./resources/js/views.js
 @ multi ./resources/js/views.js ./resources/sass/views.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m.talhabuyukakkaslar/.npm/_logs/2019-01-24T10_10_55_197Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/m.talhabuyukakkaslar/.npm/_logs/2019-01-24T10_10_55_224Z-debug.log

Ms-MacBook-Pro:emlak m.talhabuyukakkaslar$

**Comment by devmtm** [comment]
I guess you need to add laravel nova to your project package.json file.
"devDependencies": {
...
"laravel-nova": "^1.0",
...
}

**Comment by TalhaAkkas** [comment]
that didnt solved either
ill add logs here
[log.txt](https://github.com/DigitalCloud/nova-custom-views/files/2802454/log.txt)

it appears to be a babel issue 
kind regards
thanks in advance
