### ISSUE TITLE
How to remove the custom view?

### ISSUE THREAD

**Issue by Milkhan** [DigitalCloud/nova-custom-views#13]
Hi, thank you for the package!
-How one can remove the custom view(Ive tried to remove the folder but it gives error)?
- And when I add a custom view I dont see my changes on the resource. I run npm run watch in the custom view folder but nothing changes. Maybe I am doing something wrong I am not sure.
I am adding html codes between template tags nothing happens. I even remove the script tag and again its same as before, standard resource view. Where am I doing wrong? Should I register the new view somewhere?
Thank you

**Comment by devmtm** [comment]
To remove custom view, go to composer.json and remove the view from the require section and then run composer update.
