### ISSUE TITLE
Edit existing Resource page

### ISSUE THREAD

**Issue by necrojan** [DigitalCloud/nova-custom-views#19]
Is there a way to keep the existing Resource code? 

For example I have already generated a User resource, and I would like to add another table below the generated one. 

Cause afaik on the default resource page it only shows one table for that resource, so I use this custom views, but as soon as I add the 
```html

<template>
    <div>code here</code>
</template>
```

It overrides the existing resource index view completely

So is there any way to keep the existing one and just append the one's that I need?

Thank you!

**Comment by PrafullaKumarSahu** [comment]
@najaram You got any idea on it?

**Comment by necrojan** [comment]
Yes @PrafullaKumarSahu by running `php artisan nova:views user index` then once generated, 
you can use the `Index component`
```html
<resource-index resource-name="nameofresourcehere"></resource-index>
```
