### ISSUE TITLE
Command in terminal, show this: Class 'NovaCustomViews\UserViews\UserViewsServiceProvider' not found

### ISSUE THREAD

**Issue by sabid** [DigitalCloud/nova-custom-views#2]
When I execute the command

`php artisan nova:views user update`

The following error message appears.

`In ProviderRepository.php line 208:

  Class 'NovaCustomViews\UserViews\UserViewsServiceProvider' not found

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1`

![captura de pantalla 2018-11-05 a la s 6 09 59 a m](https://user-images.githubusercontent.com/3129855/47997531-cbf5e580-e0c1-11e8-92de-deb9be957747.png)

However, the package works well.

**Comment by antonioqm** [comment]
I'm getting the same error

**Comment by Hoddix** [comment]
+1

**Comment by devmtm** [comment]
You are trying to use an old version of this package. Please update the composer.json file and use 
"digitalcloud/nova-custom-views": "^1.7".

**Comment by rapitkan** [comment]
I'm getting the same error and I'm using version 1.7.

**Comment by necrojan** [comment]
I'm having the same error. using 1.7 version. Any fix on this? @devmtm

**Comment by necrojan** [comment]
It seems `composer dump-autoload` fixes it
