### ISSUE TITLE
component not shown

### ISSUE THREAD

**Issue by hufex** [DigitalCloud/nova-custom-views#23]
Hi.
First, sorry for my English.
I have my resources organized in
nova / Catalogs
---- Cases
---Company

The command you execute for the creation of the view is:
php artisan nova: views cases detail
for the resource that is in nova / Catalog / Cases

At the time of making a modification to the Detail.vue, you are leaving the code.
```
<template>
    <div> YOUR_CODE_HERE </div>
</template>
<script>
     import ResourceDetail from '@ nova / views / Detail'
     export default {
         mixins: [ResourceDetail],
     }
</script>
```

However, the code I place is never shown even if the js is compiled without errors.

Any idea that he is paying, or for not showing me the code that I put.

thanks and regards

**Comment by hufex** [comment]
so sorry. 
3 hours editing the wrong component

**Comment by mazharrehman** [comment]
I created a custom view, user Create as explained in documentation but when i click on Create butoon show a blank content area and footer nothing else, I mean not showing content even though i place code 
```
<template>
    <div> YOUR_CODE_HERE </div>
</template>
<script>
     import ResourceDetail from '@nova/views/Create'
     export default {
         mixins: [ResourceDetail],
     }
</script>
```
Further you can see in screenshot
https://gyazo.com/1e5dc384d48017290d0c4c993c83e630

Nothing is showing in content area,
