### ISSUE TITLE
laravel 6 not working

### ISSUE THREAD

**Issue by edwinencomienda** [DigitalCloud/nova-custom-views#24]
![image](https://user-images.githubusercontent.com/26597108/64757841-ced52880-d565-11e9-90e7-3751601801a1.png)

**Comment by jucargoe** [comment]
Hi.
I have resolved this issue by renaming the 'runCommand' function in the files inside the 'commands' folder of the vendor package (/vendor/digitalcloud/nova-custom-views/src/commands).

**Comment by kosmonowt** [comment]
+1 here.

would be nice to update this.

**Comment by BobbyBorisov** [comment]
@jucargoe i think its not very good to edit the vendor directory files. maybe fork the repo instead

**Comment by jucargoe** [comment]
@BobbyBorisov I know it's not good practice, but it's been the fastest way to fix the error at the moment. The best thing would be to make a pull request

**Comment by adalgdev** [comment]
+1 here.

**Comment by adalgdev** [comment]
@jucargoe can you tell me exactly what you modified and in what file? Thanks!

**Comment by jucargoe** [comment]
@adal6a 
All files in /vendor/digitalcloud/nova-custom-views/src/commands. Search functions called runCommand(...) And change the name.

**Comment by rudiullon** [comment]
I solved it copying all the classes from the `src/commands` folder into the `src/ folder`
I hope this helps

**Comment by eapostol** [comment]
Hi there- revisiting this issue @adal6a  et al mentioned "changing the name" of runCommand. What is the name and and what is it supposed to be changed to?

**Comment by eapostol** [comment]
just for clarification, I changed the method signature for the runCommand() method in each file in the /vendor/nova-custom-views/src/commands folder so that it looks like this:

`protected function runCommand($command, $path, $output){  ... } `

The error method indicates that the signature needs to be changed
