### ISSUE TITLE
ReflectionException  : Class devmtm\NovaCustomViews\ViewCommand does not exist

### ISSUE THREAD

**Issue by MikeCraig418** [DigitalCloud/nova-custom-views#3]
Can't install fully. Seems a ViewCommand class is missing from v1.2

**Comment by devmtm** [comment]
ViewCommand is no longer used and it replaced by ViewsCommand. Problem fixed in v1.4.

**Comment by otdigital-soft** [comment]
I still have that issue.

**Comment by new-user-name** [comment]
Target class [devmtm\NovaCustomViews\ViewsCommand] does not exist.
Laravel 9
