### ISSUE TITLE
Error: Module build failed: TypeError: this.setDynamic is not a function

### ISSUE THREAD

**Issue by Dontorpedo** [DigitalCloud/nova-custom-views#4]
Hi Console throws this error after creating a custom view for a resource detail page..

`Error: Module build failed: TypeError: this.setDynamic is not a function
    at PluginPass.pre (C:\laragon\www\invoices\nova-components\views\invoice\node_modules\babel-plugin-transform-runtime\lib\index.js:31:12)
    at transformFile (C:\laragon\www\invoices\node_modules\@babel\core\lib\transformation\index.js:78:27)
    at runSync (C:\laragon\www\invoices\node_modules\@babel\core\lib\transformation\index.js:45:3)
    at transformSync (C:\laragon\www\invoices\node_modules\@babel\core\lib\transform.js:43:38)
    at Object.transform (C:\laragon\www\invoices\node_modules\@babel\core\lib\transform.js:22:38)
    at transpile (C:\laragon\www\invoices\node_modules\babel-loader\lib\index.js:55:20)
    at C:\laragon\www\invoices\node_modules\babel-loader\lib\fs-cache.js:116:18
    at ReadFileContext.callback (C:\laragon\www\invoices\node_modules\babel-loader\lib\fs-cache.js:36:21)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:420:13)`

Nova admin also broken

**Comment by jishnu2292** [comment]
Im also having error
when running this `php artisan nova:views Post create`

`ERROR in /Users/.../.../node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!/Users/.../.../vendor/laravel/nova/resources/js/views/Create.vue
Module build failed: TypeError: this.setDynamic is not a function
    at PluginPass.pre (/Users/.../.../nova-components/views/post/node_modules/babel-plugin-transform-runtime/lib/index.js:31:12)
    at transformFile (/Users/.../.../node_modules/@babel/core/lib/transformation/index.js:78:27)
    at runSync (/Users/.../.../node_modules/@babel/core/lib/transformation/index.js:45:3)
    at runAsync (/Users/.../.../node_modules/@babel/core/lib/transformation/index.js:35:14)
    at process.nextTick (/Users/.../.../node_modules/@babel/core/lib/transform.js:34:34)
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
 @ /Users/.../.../vendor/laravel/nova/resources/js/views/Create.vue 4:21-395
 @ ./node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!./resources/js/views/Create.vue
 @ ./resources/js/views/Create.vue
 @ ./resources/js/views ^\.\/.*$
 @ ./resources/js/views.js
 @ multi ./resources/js/views.js ./resources/sass/views.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-12-05T07_48_47_599Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/.../.npm/_logs/2018-12-05T07_48_48_104Z-debug.log`

**Comment by devmtm** [comment]
I guess both of the two problems are environmental problems, so i need more details on your environment and your package.json file.

**Comment by tanthammar** [comment]
Same here.

```
ERROR in /Users/tina/Sites/bookons/node_modules/babel-loader/lib?{"cacheDirectory":true,"presets":[["env",{"modules":false,"targets":{"browsers":["> 2%"],"uglify":true}}]],"plugins":["transform-object-rest-spread",["transform-runtime",{"polyfill":false,"helpers":false}]]}!./node_modules/vue-loader/lib/selector.js?type=script&index=0!/Users/tina/Sites/bookons/vendor/laravel/nova/resources/js/views/Index.vue
Module build failed: TypeError: this.setDynamic is not a function

```

the package.json is installed by this package.

```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "cross-env": "^5.0.0",
        "laravel-mix": "^1.0",
        "laravel-nova": "^1.0"
    },
    "dependencies": {
        "vue": "^2.5.0"
    }
}
```


my main package.json

```
{
    "private": true,
    "scripts": {
        "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "build-translatable": "cd nova-components/Translatable && npm run dev",
        "build-translatable-prod": "cd nova-components/Translatable && npm run prod",
        "build-booking": "cd nova-components/views/booking && npm run dev",
        "build-booking-watch": "cd nova-components/views/booking && npm run watch",
        "build-booking-prod": "cd nova-components/views/booking && npm run prod",
        "build-test": "cd nova-components/views/test && npm run dev",
        "build-test-prod": "cd nova-components/views/test && npm run prod"
    },
    "dependencies": {
        "axios": "^0.18",
        "bootstrap": "^4.2.1",
        "cross-env": "^5.1",
        "jquery": "^3.2",
        "laravel-nova": "^1.0.6",
        "lodash": "^4.17.4",
        "moment": "^2.23.0",
        "npm": "^6.5.0",
        "popper.js": "^1.14.6",
        "promise": "^7.1.1",
        "rtlcss": "^2.2",
        "sweetalert": "^1.1.3",
        "trix": "^1.0.0",
        "urijs": "^1.17.0",
        "vue": "^2.5.21"
    },
    "devDependencies": {
        "@fortawesome/fontawesome-pro": "^5.6.3",
        "browser-sync": "^2.26.3",
        "browser-sync-webpack-plugin": "^2.2.2",
        "laravel-mix": "^4.0.13",
        "resolve-url-loader": "^2.3.1",
        "sass": "^1.16.0",
        "sass-loader": "^7.1.0",
        "tailwindcss": "^0.7.3",
        "vue-template-compiler": "^2.5.21"
    }
}

```

**Comment by devmtm** [comment]
This is clearly a babel issue. you can read possible solutions for this issue on:
https://github.com/babel/babel-loader/issues/560

**Comment by LevFlavien** [comment]
I resolved this by downgrading laravel-mix from `^4.0.7` to `^1.7.2`.
Then I had to add :
```
"babel-plugin-transform-vue-jsx": "^3.7.0",
"babel-plugin-syntax-jsx": "^6.18.0",
"laravel-nova": "^1.0.6",
```
All in my main app `package.json`.
I just took the same version as nova's `package.json`. I think laravel-mix 4 was fetching babel 7 packages instead of version 6 that Nova currently use.

Edit: Not sure if it's a good solution since this old version comes with a lot of security vulnerabilities (see `npm audit`). But again, it's the one Nova uses.

**Comment by tanthammar** [comment]
1. Follow the instructions in the nova documentation on how to to compile Nova's javascript for development. [https://nova.laravel.com/docs/2.0/customization/frontend.html#javascript](url)
2. Run npm install in the nova directory. (vendor/laravel/nova/)
3. cd to your nova custom views directory
4. run npm watch or dev.
5. (empty your browser cache)

No need to change anything else.

**Comment by rsiasat00** [comment]
> 1. Follow the instructions in the nova documentation on how to to compile Nova's javascript for development. [https://nova.laravel.com/docs/2.0/customization/frontend.html#javascript](url)
> 2. Run npm install in the nova directory. (vendor/laravel/nova/)
> 3. cd to your nova custom views directory
> 4. run npm watch or dev.
> 5. (empty your browser cache)
> 
> No need to change anything else.

I can't display the changes on my custom view by this approach.
I triggered npm install inside root/nova instance instead for it to work

**Comment by tanthammar** [comment]
> > 1. Follow the instructions in the nova documentation on how to to compile Nova's javascript for development. [https://nova.laravel.com/docs/2.0/customization/frontend.html#javascript](url)
> > 2. Run npm install in the nova directory. (vendor/laravel/nova/)
> > 3. cd to your nova custom views directory
> > 4. run npm watch or dev.
> > 5. (empty your browser cache)
> > 
> > No need to change anything else.
> 
> I can't display the changes on my custom view by this approach.
> I triggered npm install inside root/nova instance instead for it to work

That is what I meant with "Run npm install in the nova directory", sorry for being unclear.
