### ISSUE TITLE
Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx" specified in "..../nova/.babelrc" at 1, attempted to resolve relative to "..../nova"

### ISSUE THREAD

**Issue by rzv-me** [DigitalCloud/nova-custom-views#7]
I was able to solve this by doing
`npm install`
in the nova directory

Should it be like this?

**Comment by devmtm** [comment]
> I was able to solve this by doing
> `npm install`
> in the nova directory
> 
> Should it be like this?

Yes, it will solve it.

and another way is to add 
"babel-helper-vue-jsx-merge-props": "^2.0.3",
"babel-plugin-syntax-jsx": "^6.18.0",
"babel-plugin-transform-vue-jsx": "^3.7.0",
"babel-preset-env": "^1.7.0"
in the devDependencies section of the package.json in the laravel main directory and run npm install.
