### ISSUE TITLE
  Command "nova:views" is not defined.

### ISSUE THREAD

**Issue by simona2017** [DigitalCloud/nova-custom-views#8]
I'm using Nova 1.2.1. I've installed the package and modified the config/app.php. 
I'm getting the following error when I ran php artisan nova:views user detail

 Command "nova:views" is not defined.

**Comment by niladam** [comment]
@simona2017 did you try a `composer dump` in laravel's root?

**Comment by simona2017** [comment]
Yes and I’m still getting the same error.

**Comment by niladam** [comment]
Can you show me your `config/app.php` file ?

**Comment by niladam** [comment]
Also, try `artisan config:cache` :)

**Comment by simona2017** [comment]
You are a genius! That worked :) Thanks so much

**Comment by niladam** [comment]
Not a genius. But you're welcome -- you can probably close this now :)

**Comment by simona2017** [comment]
Multumes din suflet!

**Comment by thaifani** [comment]
not work laravel 6.8 ,nova 2.11    even when doing artisan config:cache
