### ISSUE TITLE
Where to write the custom logic 

### ISSUE THREAD

**Issue by BobbyBorisov** [DigitalCloud/nova-custom-views#9]
Hey first of all, very good package!

I wanted to ask what is the best way after we create the custom view to handle the backend logic for it? maybe do a custom api call once the form is submitted and register the controller through a Custom Tool? Is this the right path?

Cheers!

**Comment by devmtm** [comment]
Yes, sure. You can create your a custom api or you can handle the default nova api to suite your application.
soon,  will add new functionality to this package to facilitate custom logic.
